import { useEffect, useState } from 'react';
import { Header } from '../components/Header';
import { FileCard } from '../components/FileCard';
import './FilePage.css';

export function FilePage({ item, favoriteItems }) {
  const [captionText, setCaptionText] = useState('');

  useEffect(() => {
    if (item.filetype !== 'audio' || !item.captions) return;

    fetch(item.captions)
      .then((res) => res.text())
      .then((text) => setCaptionText(text.slice(2)))
      .catch(() => setCaptionText('Caption unavailable'));
  }, [item.captions, item.filetype]);

  function capitalizeStr(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  return (
    <>
      <Header
        title={item.name}
      />
      <title>{item.name}</title>

      <main>
        <FileCard
          item={item}
          favoriteItems={favoriteItems}
        />
        <div className="section">
          <h2>{item.name}</h2>
          <h3>{item.date.slice(4, 6)}/{item.date.slice(6, 8)}/{item.date.slice(0, 4)}</h3>
        </div>
        {item.filetype == "audio" && (
          <div className="section captions">
            <h2>Captions:</h2>
            <h3>(Generated by Galaxy AI)</h3>
            <pre>{captionText}</pre>
          </div>
        )}
        <div className="section">
          <h3>Location: {capitalizeStr(item.type)}</h3>
          <h3>Type: {capitalizeStr(item.filetype)}</h3>
        </div>
        <div className="section tag-section">
          <h3>Tags: </h3>
          {item.tags && item.tags.map((tag, index) => {
            return <p className={`tag tag-${index}`} key={index}>{tag}</p>;
          })}
        </div>
      </main>
    </>
  )
}