import { useEffect, useState } from 'react';
import { Header } from '../components/Header';
import { FileCard } from '../components/FileCard';
import './FilePage.css';

export function FilePage({ lists, setLists, item, favoriteItems, recentlyViewedItems, setRecentlyViewedItems }) {
  const [captionText, setCaptionText] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (item.filetype !== 'audio' || !item.captions) return;

    fetch(item.captions)
      .then((res) => res.text())
      .then((text) => setCaptionText(text.slice(2)))
      .catch(() => setCaptionText('Caption unavailable'));
  }, [item.captions, item.filetype]);

  function capitalizeStr(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  function handleLoaded() {
    setIsLoading(false);
  }

  function sharePage(e) {
    const pageUrl = window.location.href;
    const btn = e.target;
    navigator.clipboard.writeText(pageUrl);
    btn.textContent = 'Copied!';
    setTimeout(() => {
      btn.innerHTML = 'Share <b>⁖</b>';
    }, 2000);
  }

  function saveToList(e) {
    const selectElement = document.querySelector('select');
    const selectedIndex = selectElement.value;
    if (selectedIndex === '') return;
    if (lists[selectedIndex].items.includes(item)) alert('This item is already in the selected list.');

    if (!lists[selectedIndex].items.includes(item)) {
      const newLists = [...lists];
      const selectedList = newLists[selectedIndex];

      selectedList.items.push(item);
      selectedList.updatedDate = new Date().toLocaleDateString();

      setLists(newLists);
      localStorage.setItem('lists', JSON.stringify(newLists));

      e.target.textContent = 'Saved!';
      setTimeout(() => {
        e.target.textContent = 'Save';
      }, 2000);
    }
  }

  return (
    <>
      <Header
        title={item.name}
      />
      <title>{item.name}</title>

      <main>
        <FileCard
          item={item}
          favoriteItems={favoriteItems}
          recentlyViewedItems={recentlyViewedItems}
          setRecentlyViewedItems={setRecentlyViewedItems}
        />
        <div className="section">
          <h2>{item.name}</h2>
          <h3>{item.date.slice(4, 6)}/{item.date.slice(6, 8)}/{item.date.slice(0, 4)}</h3>
        </div>
        {item.filetype == "audio" && (
          <div className="section captions">
            <h2>Captions:</h2>
            <h3>(Generated by Galaxy AI)</h3>
            {isLoading ? (
              <div className="centerer">
                <img
                  className="loading-spinner"
                  src="/loading.gif"
                  alt="Loading..."
                  onLoad={handleLoaded}
                />
              </div>
            ) : (
              <pre>{captionText}</pre>
            )}
          </div>
        )}
        <div className="section">
          <h3>Location: {capitalizeStr(item.type)}</h3>
          <h3>Type: {capitalizeStr(item.filetype)}</h3>
        </div>
        <div className="section options">
          <button onClick={sharePage} className="share-btn">Share <b>⁖</b></button>

          <label>
            Save to
            <select disabled={lists.length === 0}>
              {lists.length > 0 ? (
                <>
                  {lists.map((list, index) => (
                    <option key={index} value={index}>
                      {list.name}
                    </option>
                  ))}
                </>
              ) : (
                <option value="">No lists available</option>
              )}
            </select>
            <button onClick={saveToList} disabled={lists.length === 0} className="save">Save</button>
          </label>
        </div>
        <div className="section tag-section">
          <h3>Tags: </h3>
          {item.tags && item.tags.map((tag, index) => {
            return <p className={`tag tag-${index}`} key={index}>{tag}</p>;
          })}
        </div>
      </main>
    </>
  )
}